name: Deploy NGINX to Kubernetes Cluster

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Verify Cluster Connection
      run: |
        kubectl cluster-info

    - name: Create or Update HTML ConfigMap
      run: |
        kubectl create configmap custom-html-config --from-file=index.html=site/index.html --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy or Upgrade NGINX via Helm
      run: |
        helm upgrade --install my-web oci://registry-1.docker.io/bitnamicharts/nginx \
          -f values.yaml
