name: Build and Deploy Custom Container Image

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKHUB_DEVOPS }}
        password: ${{ secrets.DOCKHUB_DEVOPS2 }}

    - name: Build and Push Docker Image
      run: |
        docker build -t hanif040/k8s-demo:${{ github.sha }} .
        docker push hanif040/k8s-demo:${{ github.sha }}

    - name: Deploy or Upgrade NGINX via Helm
      run: |
        helm upgrade --install my-web oci://registry-1.docker.io/bitnamicharts/nginx \
          --set image.repository=hanif040/k8s-demo \
          --set image.tag=${{ github.sha }} \
          --set service.type=NodePort \
          --set service.nodePorts.http=31167
